### ISSUE TITLE
compatible Elastic search 6.0 version?

### ISSUE THREAD

**Issue by emremp** [FoundatioFx/Foundatio.Parsers#11]
Hi, I run complex search filters on local installed ES 6.0 version and i cannot get right results. Did i configured something wrong or this library hasn't yet upgraded for ES 6.0.

**Comment by niemyjski** [comment]
@emremp, we've been slowly working on 6.0 support. Can you please add a test for this to our elastic6 branch / or see if this working by upgrading to our nightly nuget package for 6.x https://www.myget.org/feed/Packages/exceptionless

**Comment by niemyjski** [comment]
We just merged in support for Elastic 7.5 :)
