### ISSUE TITLE
Support of Special Characters

### ISSUE THREAD

**Issue by AzVedi** [FoundatioFx/Foundatio.Parsers#17]
Hello,

Do you have any plan to support escaping of "Special Characters"?

Thanks

**Comment by ejsmith** [comment]
It's kind of hard to update the parser right now because its built on Pegasus which doesnt work on .NET Code projects yet. My plan is to convert this to using https://github.com/datalust/superpower when I get some time.

**Comment by niemyjski** [comment]
I think the pegasus issue is now resolved. What kind of special characters do you want to escape?

**Comment by ejsmith** [comment]
Yeah, the pegasus issue is resolved. I realize this issue is from a long time again, but @AzVedi if you have specific examples then we can take a look.
