### ISSUE TITLE
Unable to parse query with escaped characters

### ISSUE THREAD

**Issue by jonnermut** [FoundatioFx/Foundatio.Parsers#49]
ElasticSearch / Lucene allows escaping characters with a backslash: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html

Feeding queries with backslashed characters in into a ElasticQueryParser them fails to parse with an exception. The same query string works when used in ElasticSearch directly. Test case below:
```
using System.Diagnostics;
using System.Threading.Tasks;
using Foundatio.Parsers.ElasticQueries;
using Foundatio.Parsers.ElasticQueries.Visitors;
using Foundatio.Parsers.LuceneQueries.Visitors;

namespace QueryEscapingTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var simple = ParseAndRewrite("normal").Result;
            Debug.Assert(simple == "normal");

            var escaped = ParseAndRewrite("\\\"escaped").Result;
            Debug.Assert(escaped == "\\\"escaped");
        }

        static async Task<string> ParseAndRewrite(string query)
        {
            QueryFieldResolver resolver = (field) =>
            {
                return field;
            };

            ElasticQueryVisitorContext context = new ElasticQueryVisitorContext { QueryType = QueryType.Query };

            var parser = new ElasticQueryParser(conf => 
                conf.UseFieldResolver(resolver)
                    .UseValidation(async info => true)
            );

            var queryNode = await parser.ParseAsync(query, context);
            return queryNode.ToString();
        }

    }
}
```

Project file: 
[QueryEscapingTest.zip](https://github.com/FoundatioFx/Foundatio.Parsers/files/4768031/QueryEscapingTest.zip)

**Comment by ejsmith** [comment]
@jonnermut this should be fixed now. Thanks for reporting!

**Comment by jonnermut** [comment]
Awesome, thanks!

**Comment by InsomniumBR** [comment]
@ejsmith could you let me know if I am doing something wrong according to the Lucene syntax here?
I grabbed the 4th line from the original bug and just moved the backslash to the end of the string.
The first 3 lines relate to what I was doing before seeing this old bug.

```
            var parser = new LuceneQueryParser();
            _ = parser.Parse("a:123"); // OK
            _ = parser.Parse("a:\"123\""); // OK
            _ = parser.Parse("a:\"123\\\""); // Exception: Unterminated quoted string

            _ = parser.Parse("\\\"escaped");  // OK
            _ = parser.Parse("\"escaped\\"); // Exception: Unterminated quoted string
```

Thank you

**Comment by niemyjski** [comment]
Would you mind creating a new issue for this @InsomniumBR.  The first one looks like it could be a bug, the last one I'm wondering how does that even compile.

**Comment by avillarrealRW** [comment]
Hello @niemyjski, I'm a coworker of @InsomniumBR and was helping out with adding some tests based on the issues we were running into. Here is the PR that I created for that, thank you!
https://github.com/FoundatioFx/Foundatio.Parsers/pull/92
