### ISSUE TITLE
dynamic mapping instead of typed class mapping

### ISSUE THREAD

**Issue by galvin1234** [FoundatioFx/Foundatio.Parsers#54]
Does your solution supports in case of dynamic mapping and dynamic search. Because when i try to search something on dynamic mapping using dynamic type then search executes but it didnt return any hits.
Or provide any test case where you are creating dynamic mapping and trying to index dynamic type and search using dynamic.

200 POST http://localhost:9200/testmes/_search?pretty=true&typed_keys=false

something like 
            var actualResponse = client.Search\<dynamic\>(d => d.Index(index).Query(q => result));
on dynamic mapping, 
instead of 
            var actualResponse = client.Search\<MyType\>(d => d.Index(index).Query(q => result));

**Comment by niemyjski** [comment]
It should work, we try and pull back mappings to resolve unknown fields. Can you please create a failing unit test for the behavior you are seeing.

**Comment by ejsmith** [comment]
@galvin1234 if you are using the current 10.0 beta release then I just found a bug with it that I am looking into.

**Comment by niemyjski** [comment]
@ejsmith is this resolved in the latest betas?

**Comment by ejsmith** [comment]
Yes. @galvin1234 let us know if you see any additional issues.
