### ISSUE TITLE
Look into Date Range parsing issue

### ISSUE THREAD

**Issue by niemyjski** [FoundatioFx/Foundatio.Parsers#6]
There is an issue in this lib or in the DateRangeExtensions project where the following can't be parsed: `processor.BuildQueryAsync("field5:[2017-01-01T00:00:00Z TO 2017-01-31} OR field1:value1", ctx)` We also cannot parse: `2019-12-01T00:00:00Z-2019-12-02T00:00:00Z`

cc: @randylsu

**Comment by ejsmith** [comment]
This works fine, but you have to escape the `:` with `\:`
