### ISSUE TITLE
Wrong field displayed by DebugQueryVisitor after using FieldResolverQueryVisitor

### ISSUE THREAD

**Issue by gjactat** [FoundatioFx/Foundatio.Parsers#60]
Hello,

First of all, thanks for your amazing query parser !
I've noticed something strange in the DebugQueryVisitor with Lucene Queries.
Consider the following code : 

```c#
string query = "Paris AND SU:(Physique OR Musique)";
LuceneQueryParser luceneQueryParser = new LuceneQueryParser();

var parsedQuery = luceneQueryParser.Parse(query);
var dico = new Dictionary<string, string>()
{
	{ "SU", "Subject" }
};
var resolvedParsedQuery = FieldResolverQueryVisitor.Run(parsedQuery, dico);
Console.WriteLine(DebugQueryVisitor.Run(resolvedParsedQuery));
```

Now, _resolvedParsedQuery_ contains a node that is pretty much the same as _parsedQuery_ except that the "SU" field has been changed to "Subject". Still, running the DebugQueryVisitor on _resolvedParsedQuery_ displays the following : 

```json
Group:
    Left - Term:
        IsQuoted: False
        Term: Paris
    Right - Group:
        IsNegated: False
        Field: SU
        Left - Term:
            IsQuoted: False
            Term: Physique
        Right - Term:
            IsQuoted: False
            Term: Musique
        Operator: Or
        Parens: true
        Data:
            @OriginalField: SU
    Operator: And
```

"Field" now has the value "Subject" in the _resolvedParsedQuery_ graph (checked with Visual Studio Spy). Which is as expected. **But the DebugQueryVisitor output still displays "SU" as Field value**. While "@OriginalField" is right.

Thanks for your attention,
Guillaume

**Comment by ejsmith** [comment]
Hmm that is strange. Could you create a failing test for this and take a look at it a bit? If you can't figure out anything then just a failing test would be really helpful.

**Comment by gjactat** [comment]
Hello,
I juste issued a pull request (my first one actually) which adds a unit test that demonstrates the problem described earlier and a proposed fix on the DebugQueryVisitor.
Hope this helps (and hope that I didn't get the DebugQueryVisitor output wrong).
