### ISSUE TITLE
Invalid queries return as valid

### ISSUE THREAD

**Issue by Issung** [FoundatioFx/Foundatio.Parsers#65]
Hi there me again, we are having some more issues with queries that elastic search does not like, but the parser of this library says they are valid, this time it has to do with unterminated regex sequences, and invalid proximity operators.

The problem is that sending these queries to ES throws an error, when this parser says they are OK.

I've made a repo with some failing tests of  the cases: https://github.com/Issung/Foundatio.Parsers
And a pull request here: https://github.com/FoundatioFx/Foundatio.Parsers/pull/64

Thanks for your speedy help on the last issue, it is much appreciated!

**Comment by ejsmith** [comment]
Thanks for reporting this issue @Issung! I'm taking a look at it now. From looking at the ES docs, it appears that if you are going to use a regex for a term expression then the start and end of the expression needs to be `/`, correct?

**Comment by ejsmith** [comment]
I don't believe `quik~2c` is supposed to be treated like a regex and therefore it is a valid expression as is.

**Comment by ejsmith** [comment]
I just tried doing `xy/z/` and it appears the way ES interprets that is that it's 2 terms `xy` and `z` as a regex. They are not evaluated together even though there aren't any spaces.

Another huge issue with this is that I don't want to get into trying to validate a regex and all the crazy syntax that it can have.

**Comment by Issung** [comment]
Hi Eric, thanks for the replies!

Re: quik~2c
This is an invalid proximity operator, not related to regex, ES tries to interpret what comes after the ~ as a number, and it finds a letter in there, making it invalid, to make the query valid a user should search for `quik~2 c` with a space after the number, at the moment your library does not catch this.

Re: Regex
I don't really expect you to validate the stuff inside the regex, I know that's a massive undertaking, but the problem is that your library currently says queries with unterminated regex are valid. I'm also about to push two more tests, once I manage to fix my internet, that shows that your library currently does not understand escaping of forward slashes, thus leading to reversed validation, in which invalid search strings return as valid, and invalid ones return as valid! Terribly confusing, hope to push them soon and help get them sorted out with you.

**Comment by Issung** [comment]
Have just updated the tests now, please have a look.

**Comment by ejsmith** [comment]
@Issung we use the proximity operator in other ways besides just numbers when doing aggregations syntax.

I really don't want to have to escape `\` in the middle of a term like this `blah/b.*/`. We currently do hierarchical tags like this tag/subtag/subsubtag I don't want to have to escape them. It seems reasonable to me that if you are going to use a regex then the term should start with a / like field1:/value.*/

**Comment by Issung** [comment]
I have a feeling we're on two different pages right now, let me explain a bit more, I'm just using your library to check if a query string is valid or not, for example, I'm using it to check that `hello\/world` is valid, which it should be, but your library says it isn't, this seems like a basic issue of the library just not escaping the character properly, because if a user searched for `hello\/world`, in a search box, they want to find a file with the name `hello/world` for example, because they escaped the forward slash to search literally for it, so are we on two different pages or am is it really super difficult? 

All I know is that some queries im testing (of which i have almost 100 in my unit tests), these queries are found as valid by elastic search itself, but invalid by your library, and sometimes the other way around, for the most part though 95% of them do match as intended. I'm just trying to weed out these edge cases with your help.

**Comment by ejsmith** [comment]
> I have a feeling we're on two different pages right now, let me explain a bit more, I'm just using your library to check if a query string is valid or not, for example, I'm using it to check that `hello\/world` is valid, which it should be, but your library says it isn't, this seems like a basic issue of the library just not escaping the character properly, because if a user searched for `hello\/world`, in a search box, they want to find a file with the name `hello/world` for example, because they escaped the forward slash to search literally for it, so are we on two different pages or am is it really super difficult?

That is fine and is a bug and we should handle that case. I just don't want to be forced to escape that because `/` is only used to start a regex in ES and is not even a reserved char in lucene. Also, I was saying that the way ES handles things like `xy/z/` is very strange. It treats it as if it was `xy OR z`. Two completely different terms. So I was saying that I'd like to enforce that a regex is always isolated so either it would be `xy /z/` with a space between or it would be `field1:/z/` with `/` as the first character showing that I am doing a regex.

> All I know is that some queries im testing (of which i have almost 100 in my unit tests), these queries are found as valid by elastic search itself, but invalid by your library, and sometimes the other way around, for the most part though 95% of them do match as intended. I'm just trying to weed out these edge cases with your help.

Completely understandable and I appreciate you finding these edge cases and helping me make the library better.

**Comment by Issung** [comment]
Thanks for understanding EJ, I'm quite fuzzy on the connection between Lucene and ES as I'm only one month into the industry and have been thrown into this search business, tasked with trying to validate search strings before sending them off, I see now from your messages that there is some difference in the syntax of lucene and ES (regex support) which will make this more difficult, perhaps i can validate the regex myself on top of using your library, unless you know of a library that could help me better?

**Comment by ejsmith** [comment]
@Issung I just merged #66 which should make any unterminated regex sequences be considered invalid. It also will allow you to escape `/` in terms. It will not treat non-numeric proximity expressions as invalid because we need to support non-numeric for aggregations. You could create a simple visitor or maybe override the built in validation visitor to have it check those.

I also did a massive test re-organization so hopefully it's easier to add future tests and for people to figure out where to add them.

Thanks for your help!
