### ISSUE TITLE
How to construct filtered elasticsearch query with aggregation

### ISSUE THREAD

**Issue by sschneider1207** [FoundatioFx/Foundatio.Parsers#7]
Hi, I'm working on building out an interface to an elasticsearch cluster, and we wanted to allow our users to specify a query, filter, and aggregation all for a single request using the lucene syntax.  

This library seems perfect, but I can't quite figure out how to take those three separate lucene queries and construct a single elasticsearch query that describes the desired result in an efficient way.

An example would be something like:
```
query = "title:dog OR title:cat";
filter = "websiteId:9 formatClassification:1";
agg = "terms:subjects~50 terms:bisacCodes~50 terms:maturityLevel terms:format";
```

Converted to elasticsearch (might have some slightly off syntax here):
```
{
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "title": {
              "value": "dog"
            }
          }
        },
        {
          "term": {
            "title": {
              "value": "cat"
            }
          }
        }
      ],
      "filter": [
        {
          "term": {
            "websiteId": {
              "value": "9"
            }
          }
        },
        {
          "term": {
            "formatClassification": {
              "value": "1"
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "subjects": {
      "terms": {
        "field": "subjects"
      }
    },
    "bisac": {
      "terms": {
        "field": "bisacCodes"
      }
    },
    "maturityLevel": {
      "terms": {
        "field": "maturityLevel"
      }
    },
    "format": {
      "terms": {
        "field": "format"
      }
    }
  }
}
```

**Comment by sschneider1207** [comment]
So far what I've tried are things along the lines of:
```csharp
const string query = "title:dog OR title:cat";
const string filter = "websiteId:9 formatClassification:1";
const string agg = "terms:subjects~50 terms:bisacCodes~50 terms:maturityLevel terms:format";

var client = new ElasticClient(new ConnectionSettings().DisableDirectStreaming().PrettyJson());
var parser = new ElasticQueryParser();
var q = await parser.BuildQueryAsync(query, new ElasticQueryVisitorContext{UseScoring = true});
var f = await parser.BuildQueryAsync(filter, new ElasticQueryVisitorContext {UseScoring = false});
var a = await parser.BuildAggregationsAsync(agg);

var resp = client.Search<Document>(d => d.Index("website").Query(x => x.Bool(b => b.Must(y => q).Filter(z => f))).Aggregations(w => a));
```

But this does not quite generate the correct query.

**Comment by niemyjski** [comment]
Hey,

You need to ensure your elasticsearch mappings are passed through (https://github.com/FoundatioFx/Foundatio.Parsers/blob/master/test/Foundatio.Parsers.LuceneQueries.Tests/AggregationParserTests.cs#L43). I'd recommend taking a look at tests, any doc examples /improvements would be greatly appreciated too :) 

What query is being generated incorrectly? If you could create a test that shows the issue you are seeing we'd be more than happy to take a look into it. We have a project located here: https://github.com/FoundatioFx/Foundatio.Repositories which integrates really nicely with the parsers and gives you a ton out of the box (especially what you are looking for). A real world sample app that uses the parsers heavily is  http://github.com/exceptionless/Exceptionless

**Comment by sschneider1207** [comment]
I missed that part about adding the elasticsearch mappings, thanks for the link.  I have looked over some of the tests, I didn't see any that fit what we were trying to create though.  I do not necessarily think the query generated is incorrect, just not what I was intending to do (the problem is I set it up incorrectly instead of the generation being wrong).

**Comment by ejsmith** [comment]
@sschneider1207 could you create a failing test and I will take a look and get it working for you.

**Comment by sschneider1207** [comment]
I don't think I'm explaining the situation very well.  The generated query is not incorrect, I just can't figure out what the proper way to generate the query I'm looking for it.  

Specifically I'm trying to figure out how to generate a query that includes a filter.  I can't find the API calls that do this, only ones that generate a query with only a filter or with only no filter.

**Comment by ejsmith** [comment]
You want a query that has a filtered non-scored part as well as a scored query part. Correct?

**Comment by sschneider1207** [comment]
Yep thats correct.  Given something like this
```csharp
const string query = "title:dog OR title:cat";
const string filter = "websiteId:9 AND formatClassification:1";
```

I'm looking for the API calls that would output
```json
{
   "query":{
      "bool":{
         "should":[
            {
               "term":{
                  "title":{
                     "value":"dog"
                  }
               }
            },
            {
               "term":{
                  "title":{
                     "value":"cat"
                  }
               }
            }
         ],
         "filter":[
            {
               "term":{
                  "websiteId":{
                     "value":"9"
                  }
               }
            },
            {
               "term":{
                  "formatClassification":{
                     "value":"1"
                  }
               }
            }
         ]
      }
   }
}
```

**Comment by ejsmith** [comment]
This is how we do that in the repositories:

https://github.com/FoundatioFx/Foundatio.Repositories/blob/master/src/Foundatio.Repositories.Elasticsearch/Queries/Builders/IElasticQueryBuilder.cs#L85

**Comment by sschneider1207** [comment]
I tried this based on that linked line:
```csharp
const string query = "title:dog OR title:cat";
const string filter = "websiteId:9 AND formatClassification:1";
const string agg = "terms:subjects~50 terms:bisacCodes~50 terms:maturityLevel terms:format";

var client = new ElasticClient(new ConnectionSettings().DisableDirectStreaming().PrettyJson());
var parser = new ElasticQueryParser();
            
var q = await parser.BuildQueryAsync(query, new ElasticQueryVisitorContext());
var f = await parser.BuildQueryAsync(filter, new ElasticQueryVisitorContext(){UseScoring = false});
var a = await parser.BuildAggregationsAsync(agg);


var boolQ = new BoolQuery
{
    Should = new[] {q},
    Filter = new[] {f}
};

var resp = client.Search<Document>(d =>
    d.Index("website")
        .Query(_ => _.Bool(__ => boolQ))
        .Aggregations(_ => a)
);

var req = Encoding.UTF8.GetString(resp.ApiCall.RequestBodyInBytes);
```

But I don't think that is the correct way you were talking about since the query is oddly formed.

**Comment by ejsmith** [comment]
Try just doing this instead:

var resp = client.Search<Document>(d =>
    d.Index("website")
        .Query(_ => boolQ)
        .Aggregations(_ => a)
);

**Comment by niemyjski** [comment]
I'm going to close this for now, if the above doesn't work please let us know and we'll reopen the issue.
