### ISSUE TITLE
Parsing Spaces in Field Names

### ISSUE THREAD

**Issue by mrkresc** [FoundatioFx/Foundatio.Parsers#70]
It looks like Foundat.io Lucene Parser doesn't like to parse spaces in field names.  

Adding a link to StackTrace as it looks like that space needs to be escaped and a screenshot showing a simple test case.

https://stackoverflow.com/questions/23257495/lucene-query-syntax-of-field-with-a-space

![image](https://user-images.githubusercontent.com/45615653/137524300-4ddd0944-d31b-4d80-800c-550d46c687e5.png)

**Comment by ejsmith** [comment]
@mrkresc curious, what do you use this library for?
