### ISSUE TITLE
Is there some sample for using the lucense query syntax with Linq query

### ISSUE THREAD

**Issue by WeihanLi** [FoundatioFx/Foundatio.Parsers#71]
I'm trying to use it to build the dynamic query but found it's a little difficult for me, so I'm wondering that if there's any sample to get started with this parser library.

Thanks

**Comment by niemyjski** [comment]
What kind of query are you trying to build up. The tests have a lot of examples

**Comment by WeihanLi** [comment]
Thanks for your reply @niemyjski , would try to look into the tests

**Comment by ejsmith** [comment]
@WeihanLi if you are trying to generate a LINQ query from the lucene syntax, then we don't have anything to do that. You could use an AST visitor to generate a database query from the lucene query. Currently we are only generating Elasticsearch queries from this library.

**Comment by WeihanLi** [comment]
@ejsmith many thanks for your info
