### ISSUE TITLE
Lucene negation symbol "!" unrecognized as special symbol

### ISSUE THREAD

**Issue by BrianFreemanAtlanta** [FoundatioFx/Foundatio.Parsers#72]
Per the docs for Lucene 2.9.4. The query expression `"jakarta apache" !"Apache Lucene"` should be equivalent to `"jakarta apache" NOT "Apache Lucene"` but instead "!" is identified as a "term" instead of the negation of "Apache Lucene".

**Comment by ejsmith** [comment]
Thanks for reporting @BrianFreemanAtlanta!
