### ISSUE TITLE
Lucene searches starting with a wildcard are identified as valid queries

### ISSUE THREAD

**Issue by BrianFreemanAtlanta** [FoundatioFx/Foundatio.Parsers#73]
Per Lucene specs 2.9.4. 

> You cannot use a * or ? symbol as the first character of a search.

When I parse a search `*hello` or `?hello` and validate the query they both come back as "valid" queries.

**Comment by ejsmith** [comment]
[Elasticsearch has an option](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-top-level-params) `allow_leading_wildcard` that allows using leading wildcards. So I can't make it fail parsing on this syntax. Would need to add a query validation option to check for this case.

**Comment by ejsmith** [comment]
Added an `AllowLeadingWildcards` option in the validator. Thanks @BrianFreemanAtlanta!
