### ISSUE TITLE
Build is failing when using version 7.17.2

### ISSUE THREAD

**Issue by colmabe** [FoundatioFx/Foundatio.Parsers#74]
When we try to build our application with the new version 7.12.2 the build fails because it can't find the package Exceptionless.DateTimeExtensions. It seams like the version 3.4.1 is not on the nuget feed.

`error NU1102: Unable to find package Exceptionless.DateTimeExtensions with version (>= 3.4.1)`

**Comment by ejsmith** [comment]
The missing nuget package has been resolved. Sorry for the delay.
