### ISSUE TITLE
DefaultOperator not applied to all terms in GenerateQueryVisitor

### ISSUE THREAD

**Issue by richardcockerill** [FoundatioFx/Foundatio.Parsers#76]
If I set the default operator on the context on a call to GenerateQueryVisitor.Run then the operator is only being applied to the left side of the first GroupNode in the graph.

eg

    IQueryNode parsedQuery = await parser.ParseAsync("term1 term2 term3);
    var context = new QueryVisitorContext { DefaultOperator = GroupOperator.And };
    string result = GenerateQueryVisitor.Run(parsedQuery, context); 

produces "term1 AND term2 term3" but should be "term1 AND term2 AND term3"

GenerateQueryVisitor needs to apply the operator to every GroupNode but this is not happening because GenerateQueryVisitor delegates to GroupNode.ToString(GroupOperator defaultOperator) which then just invokes ToString on the Left and Right.

Tests and a fix attached

[GenerateQueryVisitorDefaultOperator.patch](https://github.com/FoundatioFx/Foundatio.Parsers/files/12865450/GenerateQueryVisitorDefaultOperator.patch)

**Comment by niemyjski** [comment]
Thanks for reporting this! Would it be possible to create a pr for this given your patch.

**Comment by richardcockerill** [comment]
Thanks for responding, PR #77 created @niemyjski

**Comment by niemyjski** [comment]
Thanks again for the PR!!!
