### ISSUE TITLE
Why async?

### ISSUE THREAD

**Issue by gliljas** [FoundatioFx/Foundatio.Parsers#8]
What is the rationale behind making everything async? It's a string parser, after all.

**Comment by niemyjski** [comment]
We did this even though we really didn't want to... Because you might have async visitors / other code that need to do something async (and it's pretty ugly to have both sync and non async versions). For example, get a mapping from file etc..

**Comment by niemyjski** [comment]
I'm going to close this but feel free to continue this discussion :).

**Comment by gliljas** [comment]
OK. That may indeed be a valid use case. I just haven't encountered such a need myself, when working with other query syntax visitors. Mapping has usually been done before the visiting phase or by visiting in multiple passes. But I'm sure there may be cases where the result of an async node visitation will affect the path taken with its children.
